export default {
  LOAD_COMMENT: 'LOAD_COMMENT',
  LOAD_COMMENT_SUCCESS: 'LOAD_COMMENT_SUCCESS',
  LOAD_COMMENT_ERROR: 'LOAD_COMMENT_ERROR',
  ADD_COMMENT: 'ADD_COMMENT',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_ERROR: 'ADD_COMMENT_ERROR',
};